'use client'

import { useState } from 'react';
import { Roboto } from '@next/font/google';
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import AddToCart from './components/AddToCart';

const roboto = Roboto({
  weight: ['100', '300', '400', '500', '700', '900'],
  subsets: ['latin'],
});

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [isCartOpen, setIsCartOpen] = useState(false); 
  const toggleCart = () => {
    setIsCartOpen(!isCartOpen);
  };


  return (
    <html lang="en">
      <body
        className={roboto.className}
      >
        <main className="flex flex-col">
          <Navbar toggleCart={toggleCart}/>
          <AddToCart isCartOpen={isCartOpen} setIsCartOpen={setIsCartOpen}/>

          {children}

          <Footer/>
        </main>
      </body>
    </html>
  );
}
